### PR TITLE
Default concept label name

### LINKED ISSUE #108: default concept label is wrong
should be a split camel case of the concept name

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #108

### CODE REVIEW

File: tests/e2e/demo-spec.js [hunk 1]
```diff
@@ -24,13 +24,20 @@ describe('Report', function(){
             });
         });
         
-        it('Should create a new concept', function(){
+        it('Should create a new concept (1)', function(){
+            conceptName = 'h:helloWorldID';
+            report.taxonomy.get();
```
Comment (MatthiasBrantner) [inline tests/e2e/demo-spec.js:29]: What is this line doing?

Comment (wcandillon) [inline tests/e2e/demo-spec.js:29]: it opens the overview page. Should be fixed in #89

**Comment by MatthiasBrantner** [comment]
Approved
