### PR TITLE
rules ui refactoring + some fixes

### LINKED ISSUE #39: Merging updateConceptMap and addConceptMap
In the model API, updateConceptMap() for a concept which doesn't have synonyms yet shouldn't fail and create the appropriate entry in the concept map.

### PR DESCRIPTION
**Pull request by dknochen**
fixes #39

### CODE REVIEW

File: app/modules/report-model.js [hunk 1]
```diff
@@ -475,6 +475,32 @@ angular
         return element;
     };
 
+    var sortTreeChildren = function(children){
```
Comment (wcandillon) [inline app/modules/report-model.js:478]: I think it would be useful to have this function public (I had to copy it's source for the presentation tree)
